# Autor: Robson Vaamonde
# Site: www.procedimentosemti.com.br
# Facebook: facebook.com/ProcedimentosEmTI
# Facebook: facebook.com/BoraParaPratica
# YouTube: youtube.com/BoraParaPratica
# Linkedin: https://www.linkedin.com/in/robson-vaamonde-0b029028/
# Instagram: https://www.instagram.com/procedimentoem/?hl=pt-br
# Data de criação: 04/02/2022
# Data de atualização: 02/05/2023
# Versão: 0.03
# Testado e homologado para a versão do Ubuntu Server 20.04.x LTS x64x
#
# Configurações Globais do Prometheus
global:
  scrape_interval: 15s
  evaluation_interval: 15s
#
# Configuração do Sistema de Gerenciamento de Alertas do Prometheus
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093
#
# Configuração do Carregamento das Regras Periódicas do Prometheus 
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"
#
# Configuração do suporte ao TLS/SSL HTTPS do Prometheus
#tls_server_config:
#  cert_file: /etc/ssl/newcerts/prometheus.crt
#  key_file: /etc/ssl/private/prometheus.key
#
# Configurações do Serviço do Prometheus (alterado a Porta para 9091 para não entrar
# em conflito com o serviço do OpenFire, porta padrão do Prometheus é a 9090)
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9091"]
# - job_name: "linuxmint"
#   static_configs:
#     - targets: ["ptispo01dt001:9100"]
# - job_name: "windows10"
#   static_configs:
#     - targets: ["ptispo01dt002:9182"]